### ISSUE TITLE
Publishing this module with proper semver?

### ISSUE THREAD

**Issue by llint** [SHA65536/Hexago#3]
Thanks A LOT for the quick commits to the previous 2 issues!

However, I noticed that the published module doesn't use a proper semver, like v0.1.1 - would it be possible to do so?

Currently, my project's `go.mod` looks something like this:

```
module ebiten-test

go 1.18

require (
	github.com/SHA65536/Hexago v0.0.0-20220225124148-7ccfecfd7cc7
	github.com/fogleman/gg v1.3.0
	github.com/hajimehoshi/ebiten/v2 v2.3.3
)
```

It would be awesome, if it looks something this:

```
module ebiten-test

go 1.18

require (
	github.com/SHA65536/Hexago v0.1.0
	github.com/fogleman/gg v1.3.0
	github.com/hajimehoshi/ebiten/v2 v2.3.3
)
```

Thanks!

**Comment by SHA65536** [comment]
Hmm, I'm not sure how to do this since i'm inexperienced, i'll look into it and change that

**Comment by llint** [comment]
I haven't done that as well, but I found this link that should be helpful:

https://go.dev/doc/modules/publishing

**Comment by llint** [comment]
Btw, your latest commits worked! Although, I had to do: `go get -u github.com/SHA65536/Hexago@97b8940` to upgrade to the latest commits though.

My demo code using your Hexago / gg / ebitengine can be found here: https://github.com/llint/ebiten-demo

**Comment by SHA65536** [comment]
I think I solved it? 
Should be v0.1.0 now

**Comment by llint** [comment]
It works!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
